package com.vegawatt.core.common;

public enum ApplianceTriggerType {
    SAFE_POWER_LIMIT_BREACHED,
    CONSECUTIVE_BREACH_THRESHOLD_REACHED,
    UNUSUAL_STANDBY_CONSUMPTION,
    SESSION_DURATION_EXCEEDED,
    EXCESSIVE_DUTY_CYCLE,
    UNEXPECTED_ACTIVE_PERIOD,
    EXPECTED_ACTIVITY_MISSING,
    TELEMETRY_STALE,
    TELEMETRY_OFFLINE,
    TELEMETRY_RESUMED,
    ANOMALY_RECOVERED
}
