package com.vegawatt.core.common.events;

public enum OperationalEventType {
    ENERGY_QUOTA_80_REACHED,
    ENERGY_QUOTA_100_REACHED,
    BUDGET_QUOTA_80_REACHED,
    BUDGET_QUOTA_100_REACHED,
    PENALTY_TARIFF_ACTIVATED,
    APPLIANCE_ANOMALY_DETECTED,
    APPLIANCE_ANOMALY_RECOVERED
}
