import {
  BatteryCharging,
  Bot,
  Camera,
  Coffee,
  CookingPot,
  Droplets,
  Fan,
  Flame,
  Gamepad2,
  Home,
  Lamp,
  Laptop,
  Lightbulb,
  Microwave,
  Monitor,
  MonitorPlay,
  Plug,
  Printer,
  Projector,
  Refrigerator,
  Router,
  Sandwich,
  Shirt,
  Snowflake,
  Sparkles,
  Speaker,
  Sun,
  Tv,
  UtensilsCrossed,
  WashingMachine,
  Wifi,
  Wind,
  type LucideIcon,
} from "lucide-react";

// Backend sends only the `iconKey` string (yapılacak.md §15/§23) — it never sends a React
// component name. Keys mirror V15__seed_appliance_catalog.sql's `icon_key` column exactly.
// A handful of keys (kettle/toaster/vacuum/iron/dryer/chandelier) have no exact lucide-react
// equivalent and are mapped to the closest thematic icon instead of the generic fallback.
const ICON_KEY_MAP: Record<string, LucideIcon> = {
  refrigerator: Refrigerator,
  freezer: Snowflake,
  oven: CookingPot,
  cooktop: Flame,
  microwave: Microwave,
  coffee: Coffee,
  kettle: CookingPot,
  toaster: Sandwich,
  dishwasher: UtensilsCrossed,
  rangeHood: Wind,
  airConditioner: Fan,
  heater: Flame,
  fanHeater: Wind,
  waterHeater: Droplets,
  fan: Fan,
  airPurifier: Wind,
  humidifier: Droplets,
  washingMachine: WashingMachine,
  dryer: Wind,
  vacuum: Sparkles,
  robotVacuum: Bot,
  iron: Shirt,
  television: Tv,
  gameConsole: Gamepad2,
  soundSystem: Speaker,
  mediaBox: MonitorPlay,
  projector: Projector,
  computer: Monitor,
  laptop: Laptop,
  monitor: Monitor,
  printer: Printer,
  charger: BatteryCharging,
  modem: Router,
  router: Router,
  meshNode: Wifi,
  smartHomeHub: Home,
  camera: Camera,
  smartSpeaker: Speaker,
  lamp: Lightbulb,
  deskLamp: Lamp,
  chandelier: Lightbulb,
  smartLamp: Lightbulb,
  gardenLighting: Sun,
};

const FALLBACK_ICON: LucideIcon = Plug;

export function getApplianceCatalogIcon(iconKey: string | null | undefined): LucideIcon {
  if (!iconKey) return FALLBACK_ICON;
  return ICON_KEY_MAP[iconKey] ?? FALLBACK_ICON;
}
